name: Npm

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    paths:
      - '*.json'
      - '*.js'
      - '*.yml'
      - 'src/**'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node and run audit
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Execute npm audit
        run: npm audit || true

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node and run tests
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Execute npm ci
        run: npm ci

      - name: Execute npm run build
        run: npm run build --if-present
